-- -------------------------------------------------------------
--
-- Module: lp
-- Generated by MATLAB(R) 9.12 and Filter Design HDL Coder 3.1.11.
-- Generated on: 2023-01-25 22:48:03
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- Name: lp
-- TestBenchStimulus: impulse step ramp chirp noise 

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- Folding Factor        : 1
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time FIR Filter (real)
-- -------------------------------
-- Filter Structure  : Direct-Form FIR
-- Filter Length     : 100
-- Stable            : Yes
-- Linear Phase      : Yes (Type 2)
-- Arithmetic        : fixed
-- Numerator         : s16,20 -> [-3.125000e-02 3.125000e-02)
-- Input             : s12,15 -> [-6.250000e-02 6.250000e-02)
-- Filter Internals  : Specify Precision
--   Output          : s12,35 -> [-5.960464e-08 5.960464e-08)
--   Product         : s31,35 -> [-3.125000e-02 3.125000e-02)
--   Accumulator     : s37,35 -> [-2 2)
--   Round Mode      : convergent
--   Overflow Mode   : wrap
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY lp IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(11 DOWNTO 0); -- sfix12_En15
         filter_out                      :   OUT   std_logic_vector(11 DOWNTO 0)  -- sfix12_En35
         );

END lp;


----------------------------------------------------------------
--Module Architecture: lp
----------------------------------------------------------------
ARCHITECTURE rtl OF lp IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF signed(11 DOWNTO 0); -- sfix12_En15
  -- Constants
  CONSTANT coeff1                         : signed(15 DOWNTO 0) := to_signed(0, 16); -- sfix16_En20
  CONSTANT coeff2                         : signed(15 DOWNTO 0) := to_signed(20, 16); -- sfix16_En20
  CONSTANT coeff3                         : signed(15 DOWNTO 0) := to_signed(81, 16); -- sfix16_En20
  CONSTANT coeff4                         : signed(15 DOWNTO 0) := to_signed(181, 16); -- sfix16_En20
  CONSTANT coeff5                         : signed(15 DOWNTO 0) := to_signed(323, 16); -- sfix16_En20
  CONSTANT coeff6                         : signed(15 DOWNTO 0) := to_signed(504, 16); -- sfix16_En20
  CONSTANT coeff7                         : signed(15 DOWNTO 0) := to_signed(725, 16); -- sfix16_En20
  CONSTANT coeff8                         : signed(15 DOWNTO 0) := to_signed(985, 16); -- sfix16_En20
  CONSTANT coeff9                         : signed(15 DOWNTO 0) := to_signed(1283, 16); -- sfix16_En20
  CONSTANT coeff10                        : signed(15 DOWNTO 0) := to_signed(1618, 16); -- sfix16_En20
  CONSTANT coeff11                        : signed(15 DOWNTO 0) := to_signed(1990, 16); -- sfix16_En20
  CONSTANT coeff12                        : signed(15 DOWNTO 0) := to_signed(2396, 16); -- sfix16_En20
  CONSTANT coeff13                        : signed(15 DOWNTO 0) := to_signed(2836, 16); -- sfix16_En20
  CONSTANT coeff14                        : signed(15 DOWNTO 0) := to_signed(3307, 16); -- sfix16_En20
  CONSTANT coeff15                        : signed(15 DOWNTO 0) := to_signed(3808, 16); -- sfix16_En20
  CONSTANT coeff16                        : signed(15 DOWNTO 0) := to_signed(4338, 16); -- sfix16_En20
  CONSTANT coeff17                        : signed(15 DOWNTO 0) := to_signed(4893, 16); -- sfix16_En20
  CONSTANT coeff18                        : signed(15 DOWNTO 0) := to_signed(5472, 16); -- sfix16_En20
  CONSTANT coeff19                        : signed(15 DOWNTO 0) := to_signed(6073, 16); -- sfix16_En20
  CONSTANT coeff20                        : signed(15 DOWNTO 0) := to_signed(6693, 16); -- sfix16_En20
  CONSTANT coeff21                        : signed(15 DOWNTO 0) := to_signed(7330, 16); -- sfix16_En20
  CONSTANT coeff22                        : signed(15 DOWNTO 0) := to_signed(7981, 16); -- sfix16_En20
  CONSTANT coeff23                        : signed(15 DOWNTO 0) := to_signed(8643, 16); -- sfix16_En20
  CONSTANT coeff24                        : signed(15 DOWNTO 0) := to_signed(9315, 16); -- sfix16_En20
  CONSTANT coeff25                        : signed(15 DOWNTO 0) := to_signed(9992, 16); -- sfix16_En20
  CONSTANT coeff26                        : signed(15 DOWNTO 0) := to_signed(10673, 16); -- sfix16_En20
  CONSTANT coeff27                        : signed(15 DOWNTO 0) := to_signed(11355, 16); -- sfix16_En20
  CONSTANT coeff28                        : signed(15 DOWNTO 0) := to_signed(12034, 16); -- sfix16_En20
  CONSTANT coeff29                        : signed(15 DOWNTO 0) := to_signed(12709, 16); -- sfix16_En20
  CONSTANT coeff30                        : signed(15 DOWNTO 0) := to_signed(13375, 16); -- sfix16_En20
  CONSTANT coeff31                        : signed(15 DOWNTO 0) := to_signed(14031, 16); -- sfix16_En20
  CONSTANT coeff32                        : signed(15 DOWNTO 0) := to_signed(14674, 16); -- sfix16_En20
  CONSTANT coeff33                        : signed(15 DOWNTO 0) := to_signed(15301, 16); -- sfix16_En20
  CONSTANT coeff34                        : signed(15 DOWNTO 0) := to_signed(15909, 16); -- sfix16_En20
  CONSTANT coeff35                        : signed(15 DOWNTO 0) := to_signed(16496, 16); -- sfix16_En20
  CONSTANT coeff36                        : signed(15 DOWNTO 0) := to_signed(17059, 16); -- sfix16_En20
  CONSTANT coeff37                        : signed(15 DOWNTO 0) := to_signed(17597, 16); -- sfix16_En20
  CONSTANT coeff38                        : signed(15 DOWNTO 0) := to_signed(18106, 16); -- sfix16_En20
  CONSTANT coeff39                        : signed(15 DOWNTO 0) := to_signed(18584, 16); -- sfix16_En20
  CONSTANT coeff40                        : signed(15 DOWNTO 0) := to_signed(19031, 16); -- sfix16_En20
  CONSTANT coeff41                        : signed(15 DOWNTO 0) := to_signed(19443, 16); -- sfix16_En20
  CONSTANT coeff42                        : signed(15 DOWNTO 0) := to_signed(19819, 16); -- sfix16_En20
  CONSTANT coeff43                        : signed(15 DOWNTO 0) := to_signed(20157, 16); -- sfix16_En20
  CONSTANT coeff44                        : signed(15 DOWNTO 0) := to_signed(20456, 16); -- sfix16_En20
  CONSTANT coeff45                        : signed(15 DOWNTO 0) := to_signed(20715, 16); -- sfix16_En20
  CONSTANT coeff46                        : signed(15 DOWNTO 0) := to_signed(20932, 16); -- sfix16_En20
  CONSTANT coeff47                        : signed(15 DOWNTO 0) := to_signed(21108, 16); -- sfix16_En20
  CONSTANT coeff48                        : signed(15 DOWNTO 0) := to_signed(21240, 16); -- sfix16_En20
  CONSTANT coeff49                        : signed(15 DOWNTO 0) := to_signed(21328, 16); -- sfix16_En20
  CONSTANT coeff50                        : signed(15 DOWNTO 0) := to_signed(21372, 16); -- sfix16_En20
  CONSTANT coeff51                        : signed(15 DOWNTO 0) := to_signed(21372, 16); -- sfix16_En20
  CONSTANT coeff52                        : signed(15 DOWNTO 0) := to_signed(21328, 16); -- sfix16_En20
  CONSTANT coeff53                        : signed(15 DOWNTO 0) := to_signed(21240, 16); -- sfix16_En20
  CONSTANT coeff54                        : signed(15 DOWNTO 0) := to_signed(21108, 16); -- sfix16_En20
  CONSTANT coeff55                        : signed(15 DOWNTO 0) := to_signed(20932, 16); -- sfix16_En20
  CONSTANT coeff56                        : signed(15 DOWNTO 0) := to_signed(20715, 16); -- sfix16_En20
  CONSTANT coeff57                        : signed(15 DOWNTO 0) := to_signed(20456, 16); -- sfix16_En20
  CONSTANT coeff58                        : signed(15 DOWNTO 0) := to_signed(20157, 16); -- sfix16_En20
  CONSTANT coeff59                        : signed(15 DOWNTO 0) := to_signed(19819, 16); -- sfix16_En20
  CONSTANT coeff60                        : signed(15 DOWNTO 0) := to_signed(19443, 16); -- sfix16_En20
  CONSTANT coeff61                        : signed(15 DOWNTO 0) := to_signed(19031, 16); -- sfix16_En20
  CONSTANT coeff62                        : signed(15 DOWNTO 0) := to_signed(18584, 16); -- sfix16_En20
  CONSTANT coeff63                        : signed(15 DOWNTO 0) := to_signed(18106, 16); -- sfix16_En20
  CONSTANT coeff64                        : signed(15 DOWNTO 0) := to_signed(17597, 16); -- sfix16_En20
  CONSTANT coeff65                        : signed(15 DOWNTO 0) := to_signed(17059, 16); -- sfix16_En20
  CONSTANT coeff66                        : signed(15 DOWNTO 0) := to_signed(16496, 16); -- sfix16_En20
  CONSTANT coeff67                        : signed(15 DOWNTO 0) := to_signed(15909, 16); -- sfix16_En20
  CONSTANT coeff68                        : signed(15 DOWNTO 0) := to_signed(15301, 16); -- sfix16_En20
  CONSTANT coeff69                        : signed(15 DOWNTO 0) := to_signed(14674, 16); -- sfix16_En20
  CONSTANT coeff70                        : signed(15 DOWNTO 0) := to_signed(14031, 16); -- sfix16_En20
  CONSTANT coeff71                        : signed(15 DOWNTO 0) := to_signed(13375, 16); -- sfix16_En20
  CONSTANT coeff72                        : signed(15 DOWNTO 0) := to_signed(12709, 16); -- sfix16_En20
  CONSTANT coeff73                        : signed(15 DOWNTO 0) := to_signed(12034, 16); -- sfix16_En20
  CONSTANT coeff74                        : signed(15 DOWNTO 0) := to_signed(11355, 16); -- sfix16_En20
  CONSTANT coeff75                        : signed(15 DOWNTO 0) := to_signed(10673, 16); -- sfix16_En20
  CONSTANT coeff76                        : signed(15 DOWNTO 0) := to_signed(9992, 16); -- sfix16_En20
  CONSTANT coeff77                        : signed(15 DOWNTO 0) := to_signed(9315, 16); -- sfix16_En20
  CONSTANT coeff78                        : signed(15 DOWNTO 0) := to_signed(8643, 16); -- sfix16_En20
  CONSTANT coeff79                        : signed(15 DOWNTO 0) := to_signed(7981, 16); -- sfix16_En20
  CONSTANT coeff80                        : signed(15 DOWNTO 0) := to_signed(7330, 16); -- sfix16_En20
  CONSTANT coeff81                        : signed(15 DOWNTO 0) := to_signed(6693, 16); -- sfix16_En20
  CONSTANT coeff82                        : signed(15 DOWNTO 0) := to_signed(6073, 16); -- sfix16_En20
  CONSTANT coeff83                        : signed(15 DOWNTO 0) := to_signed(5472, 16); -- sfix16_En20
  CONSTANT coeff84                        : signed(15 DOWNTO 0) := to_signed(4893, 16); -- sfix16_En20
  CONSTANT coeff85                        : signed(15 DOWNTO 0) := to_signed(4338, 16); -- sfix16_En20
  CONSTANT coeff86                        : signed(15 DOWNTO 0) := to_signed(3808, 16); -- sfix16_En20
  CONSTANT coeff87                        : signed(15 DOWNTO 0) := to_signed(3307, 16); -- sfix16_En20
  CONSTANT coeff88                        : signed(15 DOWNTO 0) := to_signed(2836, 16); -- sfix16_En20
  CONSTANT coeff89                        : signed(15 DOWNTO 0) := to_signed(2396, 16); -- sfix16_En20
  CONSTANT coeff90                        : signed(15 DOWNTO 0) := to_signed(1990, 16); -- sfix16_En20
  CONSTANT coeff91                        : signed(15 DOWNTO 0) := to_signed(1618, 16); -- sfix16_En20
  CONSTANT coeff92                        : signed(15 DOWNTO 0) := to_signed(1283, 16); -- sfix16_En20
  CONSTANT coeff93                        : signed(15 DOWNTO 0) := to_signed(985, 16); -- sfix16_En20
  CONSTANT coeff94                        : signed(15 DOWNTO 0) := to_signed(725, 16); -- sfix16_En20
  CONSTANT coeff95                        : signed(15 DOWNTO 0) := to_signed(504, 16); -- sfix16_En20
  CONSTANT coeff96                        : signed(15 DOWNTO 0) := to_signed(323, 16); -- sfix16_En20
  CONSTANT coeff97                        : signed(15 DOWNTO 0) := to_signed(181, 16); -- sfix16_En20
  CONSTANT coeff98                        : signed(15 DOWNTO 0) := to_signed(81, 16); -- sfix16_En20
  CONSTANT coeff99                        : signed(15 DOWNTO 0) := to_signed(20, 16); -- sfix16_En20
  CONSTANT coeff100                       : signed(15 DOWNTO 0) := to_signed(0, 16); -- sfix16_En20

  -- Signals
  SIGNAL delay_pipeline                   : delay_pipeline_type(0 TO 99); -- sfix12_En15
  SIGNAL product99                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp                         : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product98                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_1                       : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product97                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_2                       : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product96                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_3                       : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product95                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_4                       : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product94                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_5                       : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product93                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_6                       : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product92                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_7                       : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product91                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_8                       : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product90                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_9                       : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product89                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_10                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product88                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_11                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product87                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_12                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product86                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_13                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product85                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_14                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product84                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_15                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product83                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_16                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product82                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_17                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product81                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_18                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product80                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_19                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product79                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_20                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product78                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_21                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product77                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_22                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product76                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_23                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product75                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_24                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product74                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_25                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product73                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_26                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product72                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_27                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product71                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_28                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product70                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_29                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product69                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_30                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product68                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_31                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product67                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_32                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product66                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_33                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product65                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_34                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product64                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_35                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product63                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_36                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product62                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_37                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product61                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_38                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product60                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_39                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product59                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_40                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product58                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_41                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product57                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_42                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product56                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_43                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product55                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_44                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product54                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_45                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product53                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_46                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product52                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_47                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product51                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_48                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product50                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_49                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product49                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_50                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product48                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_51                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product47                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_52                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product46                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_53                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product45                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_54                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product44                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_55                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product43                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_56                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product42                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_57                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product41                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_58                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product40                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_59                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product39                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_60                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product38                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_61                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product37                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_62                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product36                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_63                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product35                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_64                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product34                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_65                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product33                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_66                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product32                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_67                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product31                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_68                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product30                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_69                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product29                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_70                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product28                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_71                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product27                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_72                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product26                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_73                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product25                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_74                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product24                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_75                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product23                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_76                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product22                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_77                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product21                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_78                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product20                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_79                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product19                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_80                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product18                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_81                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product17                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_82                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product16                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_83                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product15                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_84                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product14                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_85                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product13                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_86                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product12                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_87                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product11                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_88                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product10                        : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_89                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product9                         : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_90                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product8                         : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_91                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product7                         : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_92                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product6                         : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_93                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product5                         : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_94                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product4                         : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_95                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product3                         : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_96                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL product2                         : signed(30 DOWNTO 0); -- sfix31_En35
  SIGNAL mul_temp_97                      : signed(27 DOWNTO 0); -- sfix28_En35
  SIGNAL sum1                             : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp                         : signed(31 DOWNTO 0); -- sfix32_En35
  SIGNAL sum2                             : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_1                       : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum3                             : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_2                       : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum4                             : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_3                       : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum5                             : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_4                       : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum6                             : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_5                       : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum7                             : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_6                       : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum8                             : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_7                       : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum9                             : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_8                       : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum10                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_9                       : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum11                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_10                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum12                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_11                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum13                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_12                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum14                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_13                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum15                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_14                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum16                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_15                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum17                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_16                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum18                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_17                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum19                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_18                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum20                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_19                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum21                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_20                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum22                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_21                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum23                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_22                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum24                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_23                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum25                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_24                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum26                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_25                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum27                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_26                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum28                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_27                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum29                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_28                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum30                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_29                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum31                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_30                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum32                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_31                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum33                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_32                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum34                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_33                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum35                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_34                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum36                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_35                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum37                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_36                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum38                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_37                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum39                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_38                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum40                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_39                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum41                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_40                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum42                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_41                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum43                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_42                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum44                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_43                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum45                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_44                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum46                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_45                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum47                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_46                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum48                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_47                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum49                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_48                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum50                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_49                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum51                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_50                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum52                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_51                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum53                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_52                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum54                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_53                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum55                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_54                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum56                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_55                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum57                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_56                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum58                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_57                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum59                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_58                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum60                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_59                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum61                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_60                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum62                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_61                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum63                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_62                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum64                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_63                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum65                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_64                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum66                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_65                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum67                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_66                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum68                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_67                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum69                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_68                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum70                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_69                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum71                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_70                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum72                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_71                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum73                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_72                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum74                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_73                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum75                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_74                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum76                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_75                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum77                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_76                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum78                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_77                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum79                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_78                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum80                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_79                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum81                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_80                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum82                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_81                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum83                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_82                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum84                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_83                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum85                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_84                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum86                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_85                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum87                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_86                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum88                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_87                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum89                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_88                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum90                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_89                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum91                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_90                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum92                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_91                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum93                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_92                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum94                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_93                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum95                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_94                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum96                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_95                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL sum97                            : signed(36 DOWNTO 0); -- sfix37_En35
  SIGNAL add_temp_96                      : signed(37 DOWNTO 0); -- sfix38_En35
  SIGNAL output_typeconvert               : signed(11 DOWNTO 0); -- sfix12_En35
  SIGNAL output_register                  : signed(11 DOWNTO 0); -- sfix12_En35


BEGIN

  -- Block Statements
  Delay_Pipeline_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_pipeline(0 TO 99) <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_pipeline(0) <= signed(filter_in);
        delay_pipeline(1 TO 99) <= delay_pipeline(0 TO 98);
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_process;

  mul_temp <= delay_pipeline(98) * coeff99;
  product99 <= resize(mul_temp, 31);

  mul_temp_1 <= delay_pipeline(97) * coeff98;
  product98 <= resize(mul_temp_1, 31);

  mul_temp_2 <= delay_pipeline(96) * coeff97;
  product97 <= resize(mul_temp_2, 31);

  mul_temp_3 <= delay_pipeline(95) * coeff96;
  product96 <= resize(mul_temp_3, 31);

  mul_temp_4 <= delay_pipeline(94) * coeff95;
  product95 <= resize(mul_temp_4, 31);

  mul_temp_5 <= delay_pipeline(93) * coeff94;
  product94 <= resize(mul_temp_5, 31);

  mul_temp_6 <= delay_pipeline(92) * coeff93;
  product93 <= resize(mul_temp_6, 31);

  mul_temp_7 <= delay_pipeline(91) * coeff92;
  product92 <= resize(mul_temp_7, 31);

  mul_temp_8 <= delay_pipeline(90) * coeff91;
  product91 <= resize(mul_temp_8, 31);

  mul_temp_9 <= delay_pipeline(89) * coeff90;
  product90 <= resize(mul_temp_9, 31);

  mul_temp_10 <= delay_pipeline(88) * coeff89;
  product89 <= resize(mul_temp_10, 31);

  mul_temp_11 <= delay_pipeline(87) * coeff88;
  product88 <= resize(mul_temp_11, 31);

  mul_temp_12 <= delay_pipeline(86) * coeff87;
  product87 <= resize(mul_temp_12, 31);

  mul_temp_13 <= delay_pipeline(85) * coeff86;
  product86 <= resize(mul_temp_13, 31);

  mul_temp_14 <= delay_pipeline(84) * coeff85;
  product85 <= resize(mul_temp_14, 31);

  mul_temp_15 <= delay_pipeline(83) * coeff84;
  product84 <= resize(mul_temp_15, 31);

  mul_temp_16 <= delay_pipeline(82) * coeff83;
  product83 <= resize(mul_temp_16, 31);

  mul_temp_17 <= delay_pipeline(81) * coeff82;
  product82 <= resize(mul_temp_17, 31);

  mul_temp_18 <= delay_pipeline(80) * coeff81;
  product81 <= resize(mul_temp_18, 31);

  mul_temp_19 <= delay_pipeline(79) * coeff80;
  product80 <= resize(mul_temp_19, 31);

  mul_temp_20 <= delay_pipeline(78) * coeff79;
  product79 <= resize(mul_temp_20, 31);

  mul_temp_21 <= delay_pipeline(77) * coeff78;
  product78 <= resize(mul_temp_21, 31);

  mul_temp_22 <= delay_pipeline(76) * coeff77;
  product77 <= resize(mul_temp_22, 31);

  mul_temp_23 <= delay_pipeline(75) * coeff76;
  product76 <= resize(mul_temp_23, 31);

  mul_temp_24 <= delay_pipeline(74) * coeff75;
  product75 <= resize(mul_temp_24, 31);

  mul_temp_25 <= delay_pipeline(73) * coeff74;
  product74 <= resize(mul_temp_25, 31);

  mul_temp_26 <= delay_pipeline(72) * coeff73;
  product73 <= resize(mul_temp_26, 31);

  mul_temp_27 <= delay_pipeline(71) * coeff72;
  product72 <= resize(mul_temp_27, 31);

  mul_temp_28 <= delay_pipeline(70) * coeff71;
  product71 <= resize(mul_temp_28, 31);

  mul_temp_29 <= delay_pipeline(69) * coeff70;
  product70 <= resize(mul_temp_29, 31);

  mul_temp_30 <= delay_pipeline(68) * coeff69;
  product69 <= resize(mul_temp_30, 31);

  mul_temp_31 <= delay_pipeline(67) * coeff68;
  product68 <= resize(mul_temp_31, 31);

  mul_temp_32 <= delay_pipeline(66) * coeff67;
  product67 <= resize(mul_temp_32, 31);

  mul_temp_33 <= delay_pipeline(65) * coeff66;
  product66 <= resize(mul_temp_33, 31);

  mul_temp_34 <= delay_pipeline(64) * coeff65;
  product65 <= resize(mul_temp_34, 31);

  mul_temp_35 <= delay_pipeline(63) * coeff64;
  product64 <= resize(mul_temp_35, 31);

  mul_temp_36 <= delay_pipeline(62) * coeff63;
  product63 <= resize(mul_temp_36, 31);

  mul_temp_37 <= delay_pipeline(61) * coeff62;
  product62 <= resize(mul_temp_37, 31);

  mul_temp_38 <= delay_pipeline(60) * coeff61;
  product61 <= resize(mul_temp_38, 31);

  mul_temp_39 <= delay_pipeline(59) * coeff60;
  product60 <= resize(mul_temp_39, 31);

  mul_temp_40 <= delay_pipeline(58) * coeff59;
  product59 <= resize(mul_temp_40, 31);

  mul_temp_41 <= delay_pipeline(57) * coeff58;
  product58 <= resize(mul_temp_41, 31);

  mul_temp_42 <= delay_pipeline(56) * coeff57;
  product57 <= resize(mul_temp_42, 31);

  mul_temp_43 <= delay_pipeline(55) * coeff56;
  product56 <= resize(mul_temp_43, 31);

  mul_temp_44 <= delay_pipeline(54) * coeff55;
  product55 <= resize(mul_temp_44, 31);

  mul_temp_45 <= delay_pipeline(53) * coeff54;
  product54 <= resize(mul_temp_45, 31);

  mul_temp_46 <= delay_pipeline(52) * coeff53;
  product53 <= resize(mul_temp_46, 31);

  mul_temp_47 <= delay_pipeline(51) * coeff52;
  product52 <= resize(mul_temp_47, 31);

  mul_temp_48 <= delay_pipeline(50) * coeff51;
  product51 <= resize(mul_temp_48, 31);

  mul_temp_49 <= delay_pipeline(49) * coeff50;
  product50 <= resize(mul_temp_49, 31);

  mul_temp_50 <= delay_pipeline(48) * coeff49;
  product49 <= resize(mul_temp_50, 31);

  mul_temp_51 <= delay_pipeline(47) * coeff48;
  product48 <= resize(mul_temp_51, 31);

  mul_temp_52 <= delay_pipeline(46) * coeff47;
  product47 <= resize(mul_temp_52, 31);

  mul_temp_53 <= delay_pipeline(45) * coeff46;
  product46 <= resize(mul_temp_53, 31);

  mul_temp_54 <= delay_pipeline(44) * coeff45;
  product45 <= resize(mul_temp_54, 31);

  mul_temp_55 <= delay_pipeline(43) * coeff44;
  product44 <= resize(mul_temp_55, 31);

  mul_temp_56 <= delay_pipeline(42) * coeff43;
  product43 <= resize(mul_temp_56, 31);

  mul_temp_57 <= delay_pipeline(41) * coeff42;
  product42 <= resize(mul_temp_57, 31);

  mul_temp_58 <= delay_pipeline(40) * coeff41;
  product41 <= resize(mul_temp_58, 31);

  mul_temp_59 <= delay_pipeline(39) * coeff40;
  product40 <= resize(mul_temp_59, 31);

  mul_temp_60 <= delay_pipeline(38) * coeff39;
  product39 <= resize(mul_temp_60, 31);

  mul_temp_61 <= delay_pipeline(37) * coeff38;
  product38 <= resize(mul_temp_61, 31);

  mul_temp_62 <= delay_pipeline(36) * coeff37;
  product37 <= resize(mul_temp_62, 31);

  mul_temp_63 <= delay_pipeline(35) * coeff36;
  product36 <= resize(mul_temp_63, 31);

  mul_temp_64 <= delay_pipeline(34) * coeff35;
  product35 <= resize(mul_temp_64, 31);

  mul_temp_65 <= delay_pipeline(33) * coeff34;
  product34 <= resize(mul_temp_65, 31);

  mul_temp_66 <= delay_pipeline(32) * coeff33;
  product33 <= resize(mul_temp_66, 31);

  mul_temp_67 <= delay_pipeline(31) * coeff32;
  product32 <= resize(mul_temp_67, 31);

  mul_temp_68 <= delay_pipeline(30) * coeff31;
  product31 <= resize(mul_temp_68, 31);

  mul_temp_69 <= delay_pipeline(29) * coeff30;
  product30 <= resize(mul_temp_69, 31);

  mul_temp_70 <= delay_pipeline(28) * coeff29;
  product29 <= resize(mul_temp_70, 31);

  mul_temp_71 <= delay_pipeline(27) * coeff28;
  product28 <= resize(mul_temp_71, 31);

  mul_temp_72 <= delay_pipeline(26) * coeff27;
  product27 <= resize(mul_temp_72, 31);

  mul_temp_73 <= delay_pipeline(25) * coeff26;
  product26 <= resize(mul_temp_73, 31);

  mul_temp_74 <= delay_pipeline(24) * coeff25;
  product25 <= resize(mul_temp_74, 31);

  mul_temp_75 <= delay_pipeline(23) * coeff24;
  product24 <= resize(mul_temp_75, 31);

  mul_temp_76 <= delay_pipeline(22) * coeff23;
  product23 <= resize(mul_temp_76, 31);

  mul_temp_77 <= delay_pipeline(21) * coeff22;
  product22 <= resize(mul_temp_77, 31);

  mul_temp_78 <= delay_pipeline(20) * coeff21;
  product21 <= resize(mul_temp_78, 31);

  mul_temp_79 <= delay_pipeline(19) * coeff20;
  product20 <= resize(mul_temp_79, 31);

  mul_temp_80 <= delay_pipeline(18) * coeff19;
  product19 <= resize(mul_temp_80, 31);

  mul_temp_81 <= delay_pipeline(17) * coeff18;
  product18 <= resize(mul_temp_81, 31);

  mul_temp_82 <= delay_pipeline(16) * coeff17;
  product17 <= resize(mul_temp_82, 31);

  mul_temp_83 <= delay_pipeline(15) * coeff16;
  product16 <= resize(mul_temp_83, 31);

  mul_temp_84 <= delay_pipeline(14) * coeff15;
  product15 <= resize(mul_temp_84, 31);

  mul_temp_85 <= delay_pipeline(13) * coeff14;
  product14 <= resize(mul_temp_85, 31);

  mul_temp_86 <= delay_pipeline(12) * coeff13;
  product13 <= resize(mul_temp_86, 31);

  mul_temp_87 <= delay_pipeline(11) * coeff12;
  product12 <= resize(mul_temp_87, 31);

  mul_temp_88 <= delay_pipeline(10) * coeff11;
  product11 <= resize(mul_temp_88, 31);

  mul_temp_89 <= delay_pipeline(9) * coeff10;
  product10 <= resize(mul_temp_89, 31);

  mul_temp_90 <= delay_pipeline(8) * coeff9;
  product9 <= resize(mul_temp_90, 31);

  mul_temp_91 <= delay_pipeline(7) * coeff8;
  product8 <= resize(mul_temp_91, 31);

  mul_temp_92 <= delay_pipeline(6) * coeff7;
  product7 <= resize(mul_temp_92, 31);

  mul_temp_93 <= delay_pipeline(5) * coeff6;
  product6 <= resize(mul_temp_93, 31);

  mul_temp_94 <= delay_pipeline(4) * coeff5;
  product5 <= resize(mul_temp_94, 31);

  mul_temp_95 <= delay_pipeline(3) * coeff4;
  product4 <= resize(mul_temp_95, 31);

  mul_temp_96 <= delay_pipeline(2) * coeff3;
  product3 <= resize(mul_temp_96, 31);

  mul_temp_97 <= delay_pipeline(1) * coeff2;
  product2 <= resize(mul_temp_97, 31);

  add_temp <= resize(product2, 32) + resize(product3, 32);
  sum1 <= resize(add_temp, 37);

  add_temp_1 <= resize(sum1, 38) + resize(product4, 38);
  sum2 <= add_temp_1(36 DOWNTO 0);

  add_temp_2 <= resize(sum2, 38) + resize(product5, 38);
  sum3 <= add_temp_2(36 DOWNTO 0);

  add_temp_3 <= resize(sum3, 38) + resize(product6, 38);
  sum4 <= add_temp_3(36 DOWNTO 0);

  add_temp_4 <= resize(sum4, 38) + resize(product7, 38);
  sum5 <= add_temp_4(36 DOWNTO 0);

  add_temp_5 <= resize(sum5, 38) + resize(product8, 38);
  sum6 <= add_temp_5(36 DOWNTO 0);

  add_temp_6 <= resize(sum6, 38) + resize(product9, 38);
  sum7 <= add_temp_6(36 DOWNTO 0);

  add_temp_7 <= resize(sum7, 38) + resize(product10, 38);
  sum8 <= add_temp_7(36 DOWNTO 0);

  add_temp_8 <= resize(sum8, 38) + resize(product11, 38);
  sum9 <= add_temp_8(36 DOWNTO 0);

  add_temp_9 <= resize(sum9, 38) + resize(product12, 38);
  sum10 <= add_temp_9(36 DOWNTO 0);

  add_temp_10 <= resize(sum10, 38) + resize(product13, 38);
  sum11 <= add_temp_10(36 DOWNTO 0);

  add_temp_11 <= resize(sum11, 38) + resize(product14, 38);
  sum12 <= add_temp_11(36 DOWNTO 0);

  add_temp_12 <= resize(sum12, 38) + resize(product15, 38);
  sum13 <= add_temp_12(36 DOWNTO 0);

  add_temp_13 <= resize(sum13, 38) + resize(product16, 38);
  sum14 <= add_temp_13(36 DOWNTO 0);

  add_temp_14 <= resize(sum14, 38) + resize(product17, 38);
  sum15 <= add_temp_14(36 DOWNTO 0);

  add_temp_15 <= resize(sum15, 38) + resize(product18, 38);
  sum16 <= add_temp_15(36 DOWNTO 0);

  add_temp_16 <= resize(sum16, 38) + resize(product19, 38);
  sum17 <= add_temp_16(36 DOWNTO 0);

  add_temp_17 <= resize(sum17, 38) + resize(product20, 38);
  sum18 <= add_temp_17(36 DOWNTO 0);

  add_temp_18 <= resize(sum18, 38) + resize(product21, 38);
  sum19 <= add_temp_18(36 DOWNTO 0);

  add_temp_19 <= resize(sum19, 38) + resize(product22, 38);
  sum20 <= add_temp_19(36 DOWNTO 0);

  add_temp_20 <= resize(sum20, 38) + resize(product23, 38);
  sum21 <= add_temp_20(36 DOWNTO 0);

  add_temp_21 <= resize(sum21, 38) + resize(product24, 38);
  sum22 <= add_temp_21(36 DOWNTO 0);

  add_temp_22 <= resize(sum22, 38) + resize(product25, 38);
  sum23 <= add_temp_22(36 DOWNTO 0);

  add_temp_23 <= resize(sum23, 38) + resize(product26, 38);
  sum24 <= add_temp_23(36 DOWNTO 0);

  add_temp_24 <= resize(sum24, 38) + resize(product27, 38);
  sum25 <= add_temp_24(36 DOWNTO 0);

  add_temp_25 <= resize(sum25, 38) + resize(product28, 38);
  sum26 <= add_temp_25(36 DOWNTO 0);

  add_temp_26 <= resize(sum26, 38) + resize(product29, 38);
  sum27 <= add_temp_26(36 DOWNTO 0);

  add_temp_27 <= resize(sum27, 38) + resize(product30, 38);
  sum28 <= add_temp_27(36 DOWNTO 0);

  add_temp_28 <= resize(sum28, 38) + resize(product31, 38);
  sum29 <= add_temp_28(36 DOWNTO 0);

  add_temp_29 <= resize(sum29, 38) + resize(product32, 38);
  sum30 <= add_temp_29(36 DOWNTO 0);

  add_temp_30 <= resize(sum30, 38) + resize(product33, 38);
  sum31 <= add_temp_30(36 DOWNTO 0);

  add_temp_31 <= resize(sum31, 38) + resize(product34, 38);
  sum32 <= add_temp_31(36 DOWNTO 0);

  add_temp_32 <= resize(sum32, 38) + resize(product35, 38);
  sum33 <= add_temp_32(36 DOWNTO 0);

  add_temp_33 <= resize(sum33, 38) + resize(product36, 38);
  sum34 <= add_temp_33(36 DOWNTO 0);

  add_temp_34 <= resize(sum34, 38) + resize(product37, 38);
  sum35 <= add_temp_34(36 DOWNTO 0);

  add_temp_35 <= resize(sum35, 38) + resize(product38, 38);
  sum36 <= add_temp_35(36 DOWNTO 0);

  add_temp_36 <= resize(sum36, 38) + resize(product39, 38);
  sum37 <= add_temp_36(36 DOWNTO 0);

  add_temp_37 <= resize(sum37, 38) + resize(product40, 38);
  sum38 <= add_temp_37(36 DOWNTO 0);

  add_temp_38 <= resize(sum38, 38) + resize(product41, 38);
  sum39 <= add_temp_38(36 DOWNTO 0);

  add_temp_39 <= resize(sum39, 38) + resize(product42, 38);
  sum40 <= add_temp_39(36 DOWNTO 0);

  add_temp_40 <= resize(sum40, 38) + resize(product43, 38);
  sum41 <= add_temp_40(36 DOWNTO 0);

  add_temp_41 <= resize(sum41, 38) + resize(product44, 38);
  sum42 <= add_temp_41(36 DOWNTO 0);

  add_temp_42 <= resize(sum42, 38) + resize(product45, 38);
  sum43 <= add_temp_42(36 DOWNTO 0);

  add_temp_43 <= resize(sum43, 38) + resize(product46, 38);
  sum44 <= add_temp_43(36 DOWNTO 0);

  add_temp_44 <= resize(sum44, 38) + resize(product47, 38);
  sum45 <= add_temp_44(36 DOWNTO 0);

  add_temp_45 <= resize(sum45, 38) + resize(product48, 38);
  sum46 <= add_temp_45(36 DOWNTO 0);

  add_temp_46 <= resize(sum46, 38) + resize(product49, 38);
  sum47 <= add_temp_46(36 DOWNTO 0);

  add_temp_47 <= resize(sum47, 38) + resize(product50, 38);
  sum48 <= add_temp_47(36 DOWNTO 0);

  add_temp_48 <= resize(sum48, 38) + resize(product51, 38);
  sum49 <= add_temp_48(36 DOWNTO 0);

  add_temp_49 <= resize(sum49, 38) + resize(product52, 38);
  sum50 <= add_temp_49(36 DOWNTO 0);

  add_temp_50 <= resize(sum50, 38) + resize(product53, 38);
  sum51 <= add_temp_50(36 DOWNTO 0);

  add_temp_51 <= resize(sum51, 38) + resize(product54, 38);
  sum52 <= add_temp_51(36 DOWNTO 0);

  add_temp_52 <= resize(sum52, 38) + resize(product55, 38);
  sum53 <= add_temp_52(36 DOWNTO 0);

  add_temp_53 <= resize(sum53, 38) + resize(product56, 38);
  sum54 <= add_temp_53(36 DOWNTO 0);

  add_temp_54 <= resize(sum54, 38) + resize(product57, 38);
  sum55 <= add_temp_54(36 DOWNTO 0);

  add_temp_55 <= resize(sum55, 38) + resize(product58, 38);
  sum56 <= add_temp_55(36 DOWNTO 0);

  add_temp_56 <= resize(sum56, 38) + resize(product59, 38);
  sum57 <= add_temp_56(36 DOWNTO 0);

  add_temp_57 <= resize(sum57, 38) + resize(product60, 38);
  sum58 <= add_temp_57(36 DOWNTO 0);

  add_temp_58 <= resize(sum58, 38) + resize(product61, 38);
  sum59 <= add_temp_58(36 DOWNTO 0);

  add_temp_59 <= resize(sum59, 38) + resize(product62, 38);
  sum60 <= add_temp_59(36 DOWNTO 0);

  add_temp_60 <= resize(sum60, 38) + resize(product63, 38);
  sum61 <= add_temp_60(36 DOWNTO 0);

  add_temp_61 <= resize(sum61, 38) + resize(product64, 38);
  sum62 <= add_temp_61(36 DOWNTO 0);

  add_temp_62 <= resize(sum62, 38) + resize(product65, 38);
  sum63 <= add_temp_62(36 DOWNTO 0);

  add_temp_63 <= resize(sum63, 38) + resize(product66, 38);
  sum64 <= add_temp_63(36 DOWNTO 0);

  add_temp_64 <= resize(sum64, 38) + resize(product67, 38);
  sum65 <= add_temp_64(36 DOWNTO 0);

  add_temp_65 <= resize(sum65, 38) + resize(product68, 38);
  sum66 <= add_temp_65(36 DOWNTO 0);

  add_temp_66 <= resize(sum66, 38) + resize(product69, 38);
  sum67 <= add_temp_66(36 DOWNTO 0);

  add_temp_67 <= resize(sum67, 38) + resize(product70, 38);
  sum68 <= add_temp_67(36 DOWNTO 0);

  add_temp_68 <= resize(sum68, 38) + resize(product71, 38);
  sum69 <= add_temp_68(36 DOWNTO 0);

  add_temp_69 <= resize(sum69, 38) + resize(product72, 38);
  sum70 <= add_temp_69(36 DOWNTO 0);

  add_temp_70 <= resize(sum70, 38) + resize(product73, 38);
  sum71 <= add_temp_70(36 DOWNTO 0);

  add_temp_71 <= resize(sum71, 38) + resize(product74, 38);
  sum72 <= add_temp_71(36 DOWNTO 0);

  add_temp_72 <= resize(sum72, 38) + resize(product75, 38);
  sum73 <= add_temp_72(36 DOWNTO 0);

  add_temp_73 <= resize(sum73, 38) + resize(product76, 38);
  sum74 <= add_temp_73(36 DOWNTO 0);

  add_temp_74 <= resize(sum74, 38) + resize(product77, 38);
  sum75 <= add_temp_74(36 DOWNTO 0);

  add_temp_75 <= resize(sum75, 38) + resize(product78, 38);
  sum76 <= add_temp_75(36 DOWNTO 0);

  add_temp_76 <= resize(sum76, 38) + resize(product79, 38);
  sum77 <= add_temp_76(36 DOWNTO 0);

  add_temp_77 <= resize(sum77, 38) + resize(product80, 38);
  sum78 <= add_temp_77(36 DOWNTO 0);

  add_temp_78 <= resize(sum78, 38) + resize(product81, 38);
  sum79 <= add_temp_78(36 DOWNTO 0);

  add_temp_79 <= resize(sum79, 38) + resize(product82, 38);
  sum80 <= add_temp_79(36 DOWNTO 0);

  add_temp_80 <= resize(sum80, 38) + resize(product83, 38);
  sum81 <= add_temp_80(36 DOWNTO 0);

  add_temp_81 <= resize(sum81, 38) + resize(product84, 38);
  sum82 <= add_temp_81(36 DOWNTO 0);

  add_temp_82 <= resize(sum82, 38) + resize(product85, 38);
  sum83 <= add_temp_82(36 DOWNTO 0);

  add_temp_83 <= resize(sum83, 38) + resize(product86, 38);
  sum84 <= add_temp_83(36 DOWNTO 0);

  add_temp_84 <= resize(sum84, 38) + resize(product87, 38);
  sum85 <= add_temp_84(36 DOWNTO 0);

  add_temp_85 <= resize(sum85, 38) + resize(product88, 38);
  sum86 <= add_temp_85(36 DOWNTO 0);

  add_temp_86 <= resize(sum86, 38) + resize(product89, 38);
  sum87 <= add_temp_86(36 DOWNTO 0);

  add_temp_87 <= resize(sum87, 38) + resize(product90, 38);
  sum88 <= add_temp_87(36 DOWNTO 0);

  add_temp_88 <= resize(sum88, 38) + resize(product91, 38);
  sum89 <= add_temp_88(36 DOWNTO 0);

  add_temp_89 <= resize(sum89, 38) + resize(product92, 38);
  sum90 <= add_temp_89(36 DOWNTO 0);

  add_temp_90 <= resize(sum90, 38) + resize(product93, 38);
  sum91 <= add_temp_90(36 DOWNTO 0);

  add_temp_91 <= resize(sum91, 38) + resize(product94, 38);
  sum92 <= add_temp_91(36 DOWNTO 0);

  add_temp_92 <= resize(sum92, 38) + resize(product95, 38);
  sum93 <= add_temp_92(36 DOWNTO 0);

  add_temp_93 <= resize(sum93, 38) + resize(product96, 38);
  sum94 <= add_temp_93(36 DOWNTO 0);

  add_temp_94 <= resize(sum94, 38) + resize(product97, 38);
  sum95 <= add_temp_94(36 DOWNTO 0);

  add_temp_95 <= resize(sum95, 38) + resize(product98, 38);
  sum96 <= add_temp_95(36 DOWNTO 0);

  add_temp_96 <= resize(sum96, 38) + resize(product99, 38);
  sum97 <= add_temp_96(36 DOWNTO 0);

  output_typeconvert <= sum97(11 DOWNTO 0);

  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      output_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        output_register <= output_typeconvert;
      END IF;
    END IF; 
  END PROCESS Output_Register_process;

  -- Assignment Statements
  filter_out <= std_logic_vector(output_register);
END rtl;
